[package]
name = "flussomodoro"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.45"
clap = "3.0.0-beta.5"
crossbeam = "0.8.1"
crossterm = { version = "0.22.1", features = ["event-stream"] }
derivative = "2.2.0"
enumerare = "0.1.0"
futures = "0.3.17"
notify-rust = "4.5.5"
thiserror = "1.0.30"
tokio = { version = "1.14.0", features = ["full"] }
tui = { version = "0.16.0", features = ["crossterm"], default-features = false }

[features]
